### ISSUE TITLE
typos in Peeking inside Trait Objects

### ISSUE THREAD

**Issue by tshepang** [huonw/huonw.github.io#4]
From http://huonw.github.io/blog/2015/01/peeking-inside-trait-objects:

> Trait objects, like &Foo or Box<Foo>, are normal values and that store a value of any type that implements the given trait, where the precise type can only be known at runtime.

`and that store a value` should likely be `and they store values`

>  ...two ways to get a Foo trait object out of a pointer to T look like:

`look` -> `looks`

**Comment by huonw** [comment]
Thanks!

The second one isn't a typo since it's saying that the "the two ways look like".

**Comment by tshepang** [comment]
yeah, I wasn't careful enough; thanks for the post
